"""
Small text cleaning helpers.
"""

VALID_LABELS = {"general", "medical", "drug"}

def clean_label(raw_text):
    """
    Cleans the raw text generated by the classifier model and makes sure
    it is one of the 3 valid labels. Falls back to 'general' if the
    model output is not exactly one of the expected labels.
    """
    label = raw_text.strip().lower()

    for valid in VALID_LABELS:
        if valid in label:
            return valid

    return valid
